### ISSUE TITLE
Remaining visualization issues for pilot

### ISSUE THREAD

**Issue by kentquirk** [tidepool-org/hub#13]
We have some bugs specifically related to visualization left to tackle before the pilot. The individual tasks should go into [tideline issues](https://github.com/tidepool-org/tideline/issues) and then be linked back here.
- [x] Std to Daylight time shift screws up background fill -- tidepool-org/tideline#9
- [x] SMBG images don't resize properly in Safari -- tidepool-org/tideline#11
- [x] Only display one date in the nav bar for one-day view -- tidepool-org/tideline#24
- [x] American date strings -- tidepool-org/tideline#25
- [x] Better image for the scrollbar thumb -- tidepool-org/tideline#26
- [x] Hover interaction to help pick out overlapping values -- tidepool-org/tideline#29
- [x] Tooltip timestamp rectangle width -- tidepool-org/tideline#30
- [x] Distinguish weekend days in two-week view -- tidepool-org/tideline#31
- [x] Two-week view y-axis ticks should go between pools -- tidepool-org/tideline#32
- [x] Two-week view should have a gutter -- tidepool-org/tideline#33
- [x] Responsive typography -- tidepool-org/tideline#34
- [x] Two-week view button navigation -- tidepool-org/tideline#35
- [x] Add legends -- tidepool-org/tideline#39
- [x] Add no data views for stats widget -- tidepool-org/tideline#40
- [x] Add dotted lines to show target range in BG pool fill -- tidepool-org/tideline#41
- [x] Add units to pool labels in lighter-weight font -- tidepool-org/tideline#42
